### ISSUE TITLE
ArchLinux AUR package for vault-ssh-plus

### ISSUE THREAD

**Issue by godeater** [isometry/vault-ssh-plus#12]
I've added this to the ArchLinux aur repository at https://aur.archlinux.org/packages/vault-ssh-plus-bin - would a PR with this added to the README.md be welcome?

**Comment by isometry** [comment]
Yes, please!

**Comment by godeater** [comment]
PR submitted.

Sorry it took a few goes - never had to do signed commits before, and it
took me a while to figure out!

**Comment by isometry** [comment]
Thanks for taking the time to get commit signing working! #15 is merged.
